spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: bookmsid
          uri: lb://BOOKMS
          predicates:
            - Path=/dummy-bookms/**
          filters:
            - RewritePath=/dummy-bookms/(?<path>.*), /$\{path}
        - id: issuermsid
          uri: lb://ISSUERMS
          predicates:
            - Path=/dummy-issuerms/**
          filters:
            - RewritePath=/dummy-issuerms/(?<path>.*), /$\{path}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  # health:
  #   circuitbreakers:
  #     enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
